# These are supported funding model platforms

github: [HaroonKhanAI]          # Your GitHub Sponsors username (if available)
patreon: haroonkhan             # Your Patreon username
open_collective: plantdiseaseai # Open Collective project name
ko_fi: haroonkhanai             # Ko-fi username
tidelift: ""                    # Leave empty if not used
community_bridge: ""            # Leave empty if not used
liberapay: Haroonkhan1         # Liberapay username
issuehunt: ""                   # Leave empty if not used
lfx_crowdfunding: ""            # Leave empty if not used
polar: ""                       # Leave empty if not used
buy_me_a_coffee: Haroonkhan1   # Buy Me a Coffee username
thanks_dev: ""                  # Leave empty if not used
custom: ['https://haroon-ai.tech/support'] # Any other custom links
